# estrutura de dados -  espaço na memória
lista =  [
{
'nome': 'lucas',
'idade':25,
'e-mail':'lucas@gmail.com'
},

{
'nome': 'lucas',
'idade':25,
'e-mail':'lucas@gmail.com'
},

{
'nome': 'lucas',
'idade':25,
'e-mail':'lucas@gmail.com'
},

]



# mutavel #array
l = list(range(1,1000))
lista.append(100)

variaveis  =  'a' # mutavel

tupla = () # imutavel
tupla =  1,2,3,6,10
tuplas = (1,2,3,6,9)

print(tuplas[0])
t = tuple(range(1,200))


d = { 'a':10,'b':20},c = { 'a':10,'b':20}

dicionario = {

'nome':'lucas',
'idade':10,
'e-mail':'lucas@gmail.com',
'lista':[1,2,30],
'tupla':(456465,465465),
'd':{


}


}


 

# estruturas de fluxo de controle

# funções
print()
input()
len()
sum()